sudo: required

services:
  - docker

cache:
  directories: [$HOME/.cache/snapcraft/]

script:
  - openssl aes-256-cbc -K $encrypted_3f284a8fd88a_key -iv $encrypted_3f284a8fd88a_iv
    -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
  - ./scripts/snap-in-docker.sh
  - sudo apt install snapd
  - sudo snap install *.snap --dangerous
  - /snap/bin/ipfs version

deploy:
  'on':
    branch: master
  provider: script
  script: ./scripts/push-in-docker.sh
  skip_cleanup: true
